"""initpg

Revision ID: 11e3e9dc746f
Revises: 9148ad9e152f
Create Date: 2024-02-10 20:29:40.869216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e3e9dc746f'
down_revision: Union[str, None] = '9148ad9e152f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('class_website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_class_website'), 'websites', ['class_website'], unique=False)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=False)
    op.drop_index('ix_Websites_class_website', table_name='Websites')
    op.drop_index('ix_Websites_id', table_name='Websites')
    op.drop_index('ix_Websites_url', table_name='Websites')
    op.drop_table('Websites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Websites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Websites_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Websites_pkey')
    )
    op.create_index('ix_Websites_url', 'Websites', ['url'], unique=False)
    op.create_index('ix_Websites_id', 'Websites', ['id'], unique=False)
    op.create_index('ix_Websites_class_website', 'Websites', ['class_website'], unique=False)
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_class_website'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
